---
title: "CV"
date: "2023-04-13"
---

<center>

## Dr. Jeffrey Mitchell

Department of Sociology,\
Umeå University\
jeffrey.mitchell\@umu.se \
(+46) 70 369 5667

</center>

**Current Position** - Since December 2020 Postdoctoral Fellow at the Department of Sociology, Umeå University

**Research Interests** Public opinion, immigration, institutions, social change, youth, policing, multi-level and longitudinal quantitative analysis

**Education**

-   2020 Ph.D., Sociology Umeå University, Umeå Sweden Dissertation: Prejudice in context over time: how demographic, economic and social conditions influence anti-immigrant attitudes in adolescents and adults
-   2015 M.A., Social Research and Social Justice- Sociology University of Nevada, Reno
-   2011 B.A. Sociology University of Nevada, Reno

**Professional Experience**\
*Prior Positions*

-   2016-2020 Doktorand, Umeå University
-   2015 Letter of Appointment Lecturer, University of Nevada
-   2014-2015 Teaching Assistant, University of Nevada

*Research Visits*

-   May-Oct 2018 International Visiting Research Fellow at Berlin Institute for Integration and Migration Research (BIM), Humboldt University

-   March 2018 Eurolab Visiting Scholar at GESIS Leibniz Institute for the Social Sciences

**Publications**\
*Doctoral Thesis*

-   Mitchell, J. 2020. 'Prejudice in context over time: how demographic, economic and social conditions influence anti-immigrant attitudes in adolescents and adults'. Umeå University, Department of Sociology. <http://urn.kb.se/resolve?urn=urn:nbn:se:umu:diva-167741>

*Peer reviewed publications*

-   Mitchell, J. and Chihaya, G. K. 2022. 'Track level associations between historical residential redlining and contemporary fatal encounters with the police'. *Social Science & Medicine.*
-   Czymara, C. and Mitchell, J. 2022."All Cops Are Trusted? How context and time shape immigrants' trust in the police" *Ethnic and Racial Studies*.
-   Eger, M., Mitchell, J. and Hjerm, M. 2021. '"When I was growing up": The lasting impact of immigrant presence on native-born American attitudes towards immigrants and immigration'. *European Sociological Review.* 1-20.
-   Mitchell, J. 2021. 'Social trust and anti-immigrant attitudes in Europe: A longitudinal multi-level analysis'. *Frontiers in Sociology*. 6:73.
-   Mitchell, J. 2019. 'Context and Change: A Longitudinal Analysis of Attitudes about Immigrants in Adolescence.' *Socius: Sociological Research for a Dynamic World*. 5: 1-11.
-   Mitchell, J. 2019. 'Prejudice in the classroom: A longitudinal analysis of anti- immigrant attitudes.' *Ethnic and Racial Studies*. 42(9): 1514-1533.

*Under Review*

-   Mitchell, J. and La Parra, D. 'Who gets the blame and who gets the credit? Policing, assistance, and political trust among the Roma in Europe'. Revise & Resubmit at *European Societies* Link to preprint: <https://osf.io/9vdc5/>
-   Bohman, A., Eger, M., Hjerm, M. and Mitchell, J. 'Impacts of Covid induced academic stress on self-rated health and life satisfaction' Revise and Resubmit at *European Journal of Higher Education*

*Articles In Progress*

-   Eger, M., Mitchell, J., Hjerm, M., and Bohman, A. 'Attitudinal Selection Effects in to University Education: Evidence from Sweden'

*Reports*

-   Bohman, A., Eger, M., Hjerm, M. and Mitchell, J. 2021. 'Results from the UmU-Barometer Vol. 2
-   Bohman, A., Eger, M., Hjerm, M. and Mitchell, J. 2020. 'Results from the UmU-Barometer Vol. 1

*Data*

-   Bohman, A. Eger, M. Hjerm, M. and Mitchell, J. 'UmU-Barometer: A longitudinal cohort study of university students

**Selected Presentations**

*Conferences*

-   2022 European Consortium of Sociological Research (ECSR), Amsterdam, Netherlands
-   2020 (Accepted) International Sociological Association (ISA), Porto Alegre, Brazil
-   2019 European Sociological Association (ESA) Manchester, England.
-   2018 European Consortium of Sociological Research (ECSR) Paris, France.
-   2015 Pacific Sociological Association (PSA) Long Beach, CA, USA

*Invited Talks*

-   2019 Department of Social Research and Social Justice, University of Nevada, Reno
-   2018 Department of Sociology and Social Psychology, University of Cologne
-   2018 Berlin Institute for Integration and Migration Research (BIM), Humboldt University
-   2018 GESIS Leibniz Institute for the Social Sciences

**Awards and Grants**

-   2022 Umeå university nominee for the Pro Futura Scientia XVIII
-   2021 Umeå university nominee for the Pro Futura Scientia XVII
-   2020-2023 Co-applicant. "Examining the liberalizing effect of higher education: A longitudinal cohort study of a university student population." The Swedish Research Council (VR). VR 2019- 02996. Project Grant for 4,960,000 SEK. (Main applicant: Maureen Eger; Co-applicants: Andrea Bohman and Mikael Hjerm.)
-   2018 GESIS Eurolab travel grant for 500 EUR
-   2018 Kempe travel grant for 19,000 SEK

**Teaching Experience**\

*Umeå University*

-   2022- 2023 Open Science in the Social Sciences (Ph.D. level)
-   2019-2022 Quantitative Methods (Master's level) *kurs anvarig*
-   2019-2022 Comparative Social Policy *kurs ansvarig*

*University of Nevada*

-   2015 Principles of Sociology
-   2015 Sociological Theory
-   2014 Sociology of Religion (Teaching Assistant)

*Cumulative total teaching hours: 1217*

**Professional Service**\

*Reviewer for Journals*

-   Acta Sociologica, American Sociological Review (ASR), Comparative Political Studies (CPS), Ethnic and Racial Studies (ERS), European Sociological Review (ESR), European Societies (ES), Journal of Ethnic and Migration Studies (JEMS), International Journal of Comparative Sociology (IJCS), International Migration Review (IMR), Social Science Research (SSR)

*Reviewer for Research Councils*

-   Icelandic Center for Research (rannís)

*Departmental and Institutional Service*

-   Criminology program planning group (2023)
-   SAMDOK representative for the Department of Sociology (2017-2019)
-   Umeå University Migration and Integration Network (UMIN) Board member (2019-present)

*Public Sociology*

-   Eger, Maureen and Jeffrey Mitchell (2018). 'No, the racial diversity of a country does not perfectly predict pro-immigrant attitudes'. Open Democracy. <https://tinyurl.com/2ybtr4x6>

**Skills**

*Languages*

-   Swedish
-   English (native speaker)

*Statistical Software*

-   R (expert in research and teaching)
-   STATA (expert in research)
-   SPSS (expert in teaching)
-   LimeSurvey (expert in data collection)

*Teaching Software*

-   Canvass (expert)
-   Cambro (expert)
